
package namespace.webservice.tandem4.ebut.in.htwg;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UpdateProduct_WebService", targetNamespace = "http://htwg.in.ebut.tandem4.webservice.namespace", wsdlLocation = "file:/Users/tim/workspace/WholesalerWebDemo/WebContent/wsdl/updateCatalog.wsdl")
public class UpdateProductWebService
    extends Service
{

    private final static URL UPDATEPRODUCTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException UPDATEPRODUCTWEBSERVICE_EXCEPTION;
    private final static QName UPDATEPRODUCTWEBSERVICE_QNAME = new QName("http://htwg.in.ebut.tandem4.webservice.namespace", "UpdateProduct_WebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/tim/workspace/WholesalerWebDemo/WebContent/wsdl/updateCatalog.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPDATEPRODUCTWEBSERVICE_WSDL_LOCATION = url;
        UPDATEPRODUCTWEBSERVICE_EXCEPTION = e;
    }

    public UpdateProductWebService() {
        super(__getWsdlLocation(), UPDATEPRODUCTWEBSERVICE_QNAME);
    }

    public UpdateProductWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPDATEPRODUCTWEBSERVICE_QNAME, features);
    }

    public UpdateProductWebService(URL wsdlLocation) {
        super(wsdlLocation, UPDATEPRODUCTWEBSERVICE_QNAME);
    }

    public UpdateProductWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPDATEPRODUCTWEBSERVICE_QNAME, features);
    }

    public UpdateProductWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateProductWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    	
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UpdateCatalogPortType
     */
    @WebEndpoint(name = "UpdateProduct_SOAP")
    public UpdateCatalogPortType getUpdateProductSOAP() {
        return super.getPort(new QName("http://htwg.in.ebut.tandem4.webservice.namespace", "UpdateProduct_SOAP"), UpdateCatalogPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateCatalogPortType
     */
    @WebEndpoint(name = "UpdateProduct_SOAP")
    public UpdateCatalogPortType getUpdateProductSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://htwg.in.ebut.tandem4.webservice.namespace", "UpdateProduct_SOAP"), UpdateCatalogPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPDATEPRODUCTWEBSERVICE_EXCEPTION!= null) {
            throw UPDATEPRODUCTWEBSERVICE_EXCEPTION;
        }
        return UPDATEPRODUCTWEBSERVICE_WSDL_LOCATION;
    }

}
