
package namespace.webservice.tandem4.ebut.in.htwg;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "updateFault", targetNamespace = "http://htwg.in.ebut.tandem4.webservice.namespace")
public class UpdateCatalogFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UpdateFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UpdateCatalogFault(String message, UpdateFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UpdateCatalogFault(String message, UpdateFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: namespace.webservice.tandem4.ebut.in.htwg.UpdateFaultType
     */
    public UpdateFaultType getFaultInfo() {
        return faultInfo;
    }

}
