
package namespace.webservice.tandem4.ebut.in.htwg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UpdateCatalogPortType", targetNamespace = "http://htwg.in.ebut.tandem4.webservice.namespace")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateCatalogPortType {


    /**
     * 
     * @param request
     * @return
     *     returns namespace.webservice.tandem4.ebut.in.htwg.UpdateResponseType
     * @throws UpdateCatalogFault
     */
    @WebMethod(action = "urn:#updateCatalog")
    @WebResult(name = "updateResponse", targetNamespace = "http://htwg.in.ebut.tandem4.webservice.namespace", partName = "response")
    public UpdateResponseType updateCatalog(
        @WebParam(name = "updateRequest", targetNamespace = "http://htwg.in.ebut.tandem4.webservice.namespace", partName = "request")
        UpdateRequestType request)
        throws UpdateCatalogFault
    ;

}
